apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-hpjznhgs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-hpjznhgs:2c56e5985a57c9ac66955543a196cd56ec854719@sha256:a7a81e0cb339f3c9242963bbafdd7c7ce9b7e5bef55a909b9e55e3aeb72eb386
          name: container-image
